apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secrets
  - ./cert-manager
  - ./cilium
  - ./traefik
  - ./renovate
  - ./portainer
  - ./velero
  - ./nfs-subdir-external-provisioner
  - ./cloudflare-tunnel
