apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./homepage
  - ./mealie
  - ./vaultwarden
  - ./n8n
  - ./postgresql
  - ./home-assistant
  - ./jellyfin
  - ./linkding
  - ./immich
  - ./obsidian
  - ./viral-analyzer
  - ./atuin
