apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cloudflare-tunnel
patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/envFrom
      value:
        - secretRef:
          name: staging-cloudflared
  target:
    kind: Deployment
    name: cloudflared
